// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@quickbot.io/forge'
import { wordpressBlock } from '.'
import { auth } from './auth'

export const wordpressBlockSchema = parseBlockSchema(wordpressBlock)
export const wordpressCredentialsSchema = parseBlockCredentials(wordpressBlock.id, auth.schema)
