FROM node:20-bookworm

ARG NEXT_PUBLIC_VIEWER_URL
ARG NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME
ARG NEXT_PUBLIC_SMTP_FROM
ARG NEXT_PUBLIC_STRIPE_PUBLIC_KEY
ARG NEXT_PUBLIC_GOOGLE_API_KEY
ARG NEXT_PUBLIC_GIPHY_API_KEY
ARG DATABASE_URL
ARG ENCRYPTION_SECRET 
ARG NEXTAUTH_URL
ARG SCOPE

ENV NEXT_PUBLIC_VIEWER_URL=${NEXT_PUBLIC_VIEWER_URL}
ENV NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME=${NEXT_PUBLIC_VERCEL_VIEWER_PROJECT_NAME}
ENV NEXT_PUBLIC_SMTP_FROM=${NEXT_PUBLIC_SMTP_FROM}
ENV NEXT_PUBLIC_STRIPE_PUBLIC_KEY=${NEXT_PUBLIC_STRIPE_PUBLIC_KEY}
ENV NEXT_PUBLIC_GOOGLE_API_KEY=${NEXT_PUBLIC_GOOGLE_API_KEY}
ENV NEXT_PUBLIC_GIPHY_API_KEY=${NEXT_PUBLIC_GIPHY_API_KEY}
ENV DATABASE_URL=${DATABASE_URL}
ENV ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV SCOPE=${SCOPE}

WORKDIR /app

COPY scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

COPY ./apps/${SCOPE}/.next/standalone ./
COPY ./apps/${SCOPE}/.next/static ./apps/${SCOPE}/.next/static
COPY ./apps/${SCOPE}/public ./apps/${SCOPE}/public

EXPOSE 3000
CMD ["/entrypoint.sh"]