// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@quickbot.io/forge'
import { segmentBlock } from '.'
import { auth } from './auth'

export const segmentBlockSchema = parseBlockSchema(segmentBlock)
export const segmentCredentialsSchema = parseBlockCredentials(segmentBlock.id, auth.schema)
