// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@quickbot.io/forge'
import { twilioComBlock } from '.'
import { auth } from './auth'

export const twilioComBlockSchema = parseBlockSchema(twilioComBlock)
export const twilioComCredentialsSchema = parseBlockCredentials(twilioComBlock.id, auth.schema)
