// Do not edit this file manually
import { parseBlockCredentials, parseBlockSchema } from '@quickbot.io/forge'
import { openRouterBlock } from '.'
import { auth } from './auth'

export const openRouterBlockSchema = parseBlockSchema(openRouterBlock)
export const openRouterCredentialsSchema = parseBlockCredentials(openRouterBlock.id, auth.schema)
