// Do not edit this file manually
import { anthropicBlock } from '@quickbot.io/anthropic-block'
import { openRouterBlock } from '@quickbot.io/open-router-block'
import { togetherAiBlock } from '@quickbot.io/together-ai-block'
import { elevenlabsBlock } from '@quickbot.io/elevenlabs-block'
import { difyAiBlock } from '@quickbot.io/dify-ai-block'
import { mistralBlock } from '@quickbot.io/mistral-block'
import { qrCodeBlock } from '@quickbot.io/qrcode-block'
import { chatNodeBlock } from '@quickbot.io/chat-node-block'
import { calComBlock } from '@quickbot.io/cal-com-block'
import { openAIBlock } from '@quickbot.io/openai-block'
import { nocodbBlock } from '@quickbot.io/nocodb-block'
import { segmentBlock } from '@quickbot.io/segment-block'
import { groqBlock } from '@quickbot.io/groq-block'
import { twilioComBlock } from '@quickbot.io/twilio-com-block'
import { wooCommerceBlock } from '@quickbot.io/woocommerce-block'
import { wordpressBlock } from '@quickbot.io/wordpress-block'
import { freshDeskBlock } from '@quickbot.io/freshdesk-block'
import { zohoCrmBlock } from '@quickbot.io/zoho-crm-block'

export const forgedBlocks = {
  [openAIBlock.id]: openAIBlock,
  [calComBlock.id]: calComBlock,
  [chatNodeBlock.id]: chatNodeBlock,
  [qrCodeBlock.id]: qrCodeBlock,
  [difyAiBlock.id]: difyAiBlock,
  [mistralBlock.id]: mistralBlock,
  [elevenlabsBlock.id]: elevenlabsBlock,
  [anthropicBlock.id]: anthropicBlock,
  [togetherAiBlock.id]: togetherAiBlock,
  [openRouterBlock.id]: openRouterBlock,
  [nocodbBlock.id]: nocodbBlock,
  [segmentBlock.id]: segmentBlock,
  [groqBlock.id]: groqBlock,
  [twilioComBlock.id]: twilioComBlock,
  [wordpressBlock.id]: wordpressBlock,
  [wooCommerceBlock.id]: wooCommerceBlock,
  [freshDeskBlock.id]: freshDeskBlock,
  [zohoCrmBlock.id]: zohoCrmBlock,
}
