// Do not edit this file manually
import { anthropicBlock } from '@quickbot.io/anthropic-block'
import { anthropicBlockSchema } from '@quickbot.io/anthropic-block/schemas'
import { calComBlock } from '@quickbot.io/cal-com-block'
import { calComBlockSchema } from '@quickbot.io/cal-com-block/schemas'
import { chatNodeBlock } from '@quickbot.io/chat-node-block'
import { chatNodeBlockSchema } from '@quickbot.io/chat-node-block/schemas'
import { difyAiBlock } from '@quickbot.io/dify-ai-block'
import { difyAiBlockSchema } from '@quickbot.io/dify-ai-block/schemas'
import { elevenlabsBlock } from '@quickbot.io/elevenlabs-block'
import { elevenlabsBlockSchema } from '@quickbot.io/elevenlabs-block/schemas'
import { mistralBlock } from '@quickbot.io/mistral-block'
import { mistralBlockSchema } from '@quickbot.io/mistral-block/schemas'
import { openRouterBlock } from '@quickbot.io/open-router-block'
import { openRouterBlockSchema } from '@quickbot.io/open-router-block/schemas'
import { openAIBlock } from '@quickbot.io/openai-block'
import { openAIBlockSchema } from '@quickbot.io/openai-block/schemas'
import { qrCodeBlock } from '@quickbot.io/qrcode-block'
import { qrCodeBlockSchema } from '@quickbot.io/qrcode-block/schemas'
import { togetherAiBlock } from '@quickbot.io/together-ai-block'
import { togetherAiBlockSchema } from '@quickbot.io/together-ai-block/schemas'
import { nocodbBlock } from '@quickbot.io/nocodb-block'
import { nocodbBlockSchema } from '@quickbot.io/nocodb-block/schemas'
import { segmentBlock } from '@quickbot.io/segment-block'
import { segmentBlockSchema } from '@quickbot.io/segment-block/schemas'
import { groqBlock } from '@quickbot.io/groq-block'
import { groqBlockSchema } from '@quickbot.io/groq-block/schemas'
import { twilioComBlock } from '@quickbot.io/twilio-com-block'
import { twilioComBlockSchema } from '@quickbot.io/twilio-com-block/schemas'
import { wooCommerceBlock } from '@quickbot.io/woocommerce-block'
import { wooCommerceBlockSchema } from '@quickbot.io/woocommerce-block/schemas'
import { wordpressBlock } from '@quickbot.io/wordpress-block'
import { wordpressBlockSchema } from '@quickbot.io/wordpress-block/schemas'
import { freshDeskBlock } from '@quickbot.io/freshdesk-block'
import { freshDeskBlockSchema } from '@quickbot.io/freshdesk-block/schemas'
import { zohoCrmBlock } from '@quickbot.io/zoho-crm-block'
import { zohoCrmBlockSchema } from '@quickbot.io/zoho-crm-block/schemas'

export const forgedBlockSchemas = {
  [openAIBlock.id]: openAIBlockSchema,
  [calComBlock.id]: calComBlockSchema,
  [chatNodeBlock.id]: chatNodeBlockSchema,
  [qrCodeBlock.id]: qrCodeBlockSchema,
  [difyAiBlock.id]: difyAiBlockSchema,
  [mistralBlock.id]: mistralBlockSchema,
  [elevenlabsBlock.id]: elevenlabsBlockSchema,
  [anthropicBlock.id]: anthropicBlockSchema,
  [togetherAiBlock.id]: togetherAiBlockSchema,
  [openRouterBlock.id]: openRouterBlockSchema,
  [nocodbBlock.id]: nocodbBlockSchema,
  [segmentBlock.id]: segmentBlockSchema,
  [groqBlock.id]: groqBlockSchema,
  [twilioComBlock.id]: twilioComBlockSchema,
  [wordpressBlock.id]: wordpressBlockSchema,
  [wooCommerceBlock.id]: wooCommerceBlockSchema,
  [freshDeskBlock.id]: freshDeskBlockSchema,
  [zohoCrmBlock.id]: zohoCrmBlockSchema,
}
