export const countries = [
  { value: 'DZ', label: 'Algeria (+213)' },
  { value: 'AD', label: 'Andorra (+376)' },
  { value: 'AO', label: 'Angola (+244)' },
  { value: 'AI', label: 'Anguilla (+1264)' },
  { value: 'AG', label: 'Antigua & Barbuda (+1268)' },
  { value: 'AR', label: 'Argentina (+54)' },
  { value: 'AM', label: 'Armenia (+374)' },
  { value: 'AW', label: 'Aruba (+297)' },
  { value: 'AU', label: 'Australia (+61)' },
  { value: 'AT', label: 'Austria (+43)' },
  { value: 'AZ', label: 'Azerbaijan (+994)' },
  { value: 'BS', label: 'Bahamas (+1242)' },
  { value: 'BH', label: 'Bahrain (+973)' },
  { value: 'BD', label: 'Bangladesh (+880)' },
  { value: 'BB', label: 'Barbados (+1246)' },
  { value: 'BY', label: 'Belarus (+375)' },
  { value: 'BE', label: 'Belgium (+32)' },
  { value: 'BZ', label: 'Belize (+501)' },
  { value: 'BJ', label: 'Benin (+229)' },
  { value: 'BM', label: 'Bermuda (+1441)' },
  { value: 'BT', label: 'Bhutan (+975)' },
  { value: 'BO', label: 'Bolivia (+591)' },
  { value: 'BA', label: 'Bosnia Herzegovina (+387)' },
  { value: 'BW', label: 'Botswana (+267)' },
  { value: 'BR', label: 'Brazil (+55)' },
  { value: 'BN', label: 'Brunei (+673)' },
  { value: 'BG', label: 'Bulgaria (+359)' },
  { value: 'BF', label: 'Burkina Faso (+226)' },
  { value: 'BI', label: 'Burundi (+257)' },
  { value: 'KH', label: 'Cambodia (+855)' },
  { value: 'CM', label: 'Cameroon (+237)' },
  { value: 'CA', label: 'Canada (+1)' },
  { value: 'CV', label: 'Cape Verde Islands (+238)' },
  { value: 'KY', label: 'Cayman Islands (+1345)' },
  { value: 'CF', label: 'Central African Republic (+236)' },
  { value: 'CL', label: 'Chile (+56)' },
  { value: 'CN', label: 'China (+86)' },
  { value: 'CO', label: 'Colombia (+57)' },
  { value: 'KM', label: 'Comoros (+269)' },
  { value: 'CG', label: 'Congo (+242)' },
  { value: 'CK', label: 'Cook Islands (+682)' },
  { value: 'CR', label: 'Costa Rica (+506)' },
  { value: 'HR', label: 'Croatia (+385)' },
  { value: 'CU', label: 'Cuba (+53)' },
  { value: 'CY', label: 'Cyprus North (+90392)' },
  { value: 'CY', label: 'Cyprus South (+357)' },
  { value: 'CZ', label: 'Czech Republic (+42)' },
  { value: 'DK', label: 'Denmark (+45)' },
  { value: 'DJ', label: 'Djibouti (+253)' },
  { value: 'DM', label: 'Dominica (+1809)' },
  { value: 'DO', label: 'Dominican Republic (+18XX)' },
  { value: 'EC', label: 'Ecuador (+593)' },
  { value: 'EG', label: 'Egypt (+20)' },
  { value: 'SV', label: 'El Salvador (+503)' },
  { value: 'GQ', label: 'Equatorial Guinea (+240)' },
  { value: 'ER', label: 'Eritrea (+291)' },
  { value: 'EE', label: 'Estonia (+372)' },
  { value: 'ET', label: 'Ethiopia (+251)' },
  { value: 'FK', label: 'Falkland Islands (+500)' },
  { value: 'FO', label: 'Faroe Islands (+298)' },
  { value: 'FJ', label: 'Fiji (+679)' },
  { value: 'FI', label: 'Finland (+358)' },
  { value: 'FR', label: 'France (+33)' },
  { value: 'GF', label: 'French Guiana (+594)' },
  { value: 'PF', label: 'French Polynesia (+689)' },
  { value: 'GA', label: 'Gabon (+241)' },
  { value: 'GM', label: 'Gambia (+220)' },
  { value: 'GE', label: 'Georgia (+7880)' },
  { value: 'DE', label: 'Germany (+49)' },
  { value: 'GH', label: 'Ghana (+233)' },
  { value: 'GI', label: 'Gibraltar (+350)' },
  { value: 'GR', label: 'Greece (+30)' },
  { value: 'GL', label: 'Greenland (+299)' },
  { value: 'GD', label: 'Grenada (+1473)' },
  { value: 'GP', label: 'Guadeloupe (+590)' },
  { value: 'GU', label: 'Guam (+671)' },
  { value: 'GT', label: 'Guatemala (+502)' },
  { value: 'GN', label: 'Guinea (+224)' },
  { value: 'GW', label: 'Guinea - Bissau (+245)' },
  { value: 'GY', label: 'Guyana (+592)' },
  { value: 'HT', label: 'Haiti (+509)' },
  { value: 'HN', label: 'Honduras (+504)' },
  { value: 'HK', label: 'Hong Kong (+852)' },
  { value: 'HU', label: 'Hungary (+36)' },
  { value: 'IS', label: 'Iceland (+354)' },
  { value: 'IN', label: 'India (+91)' },
  { value: 'ID', label: 'Indonesia (+62)' },
  { value: 'IR', label: 'Iran (+98)' },
  { value: 'IQ', label: 'Iraq (+964)' },
  { value: 'IE', label: 'Ireland (+353)' },
  { value: 'IL', label: 'Israel (+972)' },
  { value: 'IT', label: 'Italy (+39)' },
  { value: 'JM', label: 'Jamaica (+1876)' },
  { value: 'JP', label: 'Japan (+81)' },
  { value: 'JO', label: 'Jordan (+962)' },
  { value: 'KZ', label: 'Kazakhstan (+7)' },
  { value: 'KE', label: 'Kenya (+254)' },
  { value: 'KI', label: 'Kiribati (+686)' },
  { value: 'KP', label: 'Korea North (+850)' },
  { value: 'KR', label: 'Korea South (+82)' },
  { value: 'KW', label: 'Kuwait (+965)' },
  { value: 'KG', label: 'Kyrgyzstan (+996)' },
  { value: 'LA', label: 'Laos (+856)' },
  { value: 'LV', label: 'Latvia (+371)' },
  { value: 'LB', label: 'Lebanon (+961)' },
  { value: 'LS', label: 'Lesotho (+266)' },
  { value: 'LR', label: 'Liberia (+231)' },
  { value: 'LY', label: 'Libya (+218)' },
  { value: 'LI', label: 'Liechtenstein (+417)' },
  { value: 'LT', label: 'Lithuania (+370)' },
  { value: 'LU', label: 'Luxembourg (+352)' },
  { value: 'MO', label: 'Macao (+853)' },
  { value: 'MK', label: 'Macedonia (+389)' },
  { value: 'MG', label: 'Madagascar (+261)' },
  { value: 'MW', label: 'Malawi (+265)' },
  { value: 'MY', label: 'Malaysia (+60)' },
  { value: 'MV', label: 'Maldives (+960)' },
  { value: 'ML', label: 'Mali (+223)' },
  { value: 'MT', label: 'Malta (+356)' },
  { value: 'MH', label: 'Marshall Islands (+692)' },
  { value: 'MQ', label: 'Martinique (+596)' },
  { value: 'MR', label: 'Mauritania (+222)' },
  { value: 'YT', label: 'Mayotte (+269)' },
  { value: 'MX', label: 'Mexico (+52)' },
  { value: 'FM', label: 'Micronesia (+691)' },
  { value: 'MD', label: 'Moldova (+373)' },
  { value: 'MC', label: 'Monaco (+377)' },
  { value: 'MN', label: 'Mongolia (+976)' },
  { value: 'MS', label: 'Montserrat (+1664)' },
  { value: 'MA', label: 'Morocco (+212)' },
  { value: 'MZ', label: 'Mozambique (+258)' },
  { value: 'MN', label: 'Myanmar (+95)' },
  { value: 'NA', label: 'Namibia (+264)' },
  { value: 'NR', label: 'Nauru (+674)' },
  { value: 'NP', label: 'Nepal (+977)' },
  { value: 'NL', label: 'Netherlands (+31)' },
  { value: 'NC', label: 'New Caledonia (+687)' },
  { value: 'NZ', label: 'New Zealand (+64)' },
  { value: 'NI', label: 'Nicaragua (+505)' },
  { value: 'NE', label: 'Niger (+227)' },
  { value: 'NG', label: 'Nigeria (+234)' },
  { value: 'NU', label: 'Niue (+683)' },
  { value: 'NF', label: 'Norfolk Islands (+672)' },
  { value: 'NP', label: 'Northern Marianas (+670)' },
  { value: 'NO', label: 'Norway (+47)' },
  { value: 'OM', label: 'Oman (+968)' },
  { value: 'PW', label: 'Palau (+680)' },
  { value: 'PA', label: 'Panama (+507)' },
  { value: 'PG', label: 'Papua New Guinea (+675)' },
  { value: 'PY', label: 'Paraguay (+595)' },
  { value: 'PE', label: 'Peru (+51)' },
  { value: 'PH', label: 'Philippines (+63)' },
  { value: 'PL', label: 'Poland (+48)' },
  { value: 'PT', label: 'Portugal (+351)' },
  { value: 'PR', label: 'Puerto Rico (+1787)' },
  { value: 'QA', label: 'Qatar (+974)' },
  { value: 'RE', label: 'Reunion (+262)' },
  { value: 'RO', label: 'Romania (+40)' },
  { value: 'RU', label: 'Russia (+7)' },
  { value: 'RW', label: 'Rwanda (+250)' },
  { value: 'SM', label: 'San Marino (+378)' },
  { value: 'ST', label: 'Sao Tome & Principe (+239)' },
  { value: 'SA', label: 'Saudi Arabia (+966)' },
  { value: 'SN', label: 'Senegal (+221)' },
  { value: 'CS', label: 'Serbia (+381)' },
  { value: 'SC', label: 'Seychelles (+248)' },
  { value: 'SL', label: 'Sierra Leone (+232)' },
  { value: 'SG', label: 'Singapore (+65)' },
  { value: 'SK', label: 'Slovak Republic (+421)' },
  { value: 'SI', label: 'Slovenia (+386)' },
  { value: 'SB', label: 'Solomon Islands (+677)' },
  { value: 'SO', label: 'Somalia (+252)' },
  { value: 'ZA', label: 'South Africa (+27)' },
  { value: 'ES', label: 'Spain (+34)' },
  { value: 'LK', label: 'Sri Lanka (+94)' },
  { value: 'SH', label: 'St. Helena (+290)' },
  { value: 'KN', label: 'St. Kitts (+1869)' },
  { value: 'SC', label: 'St. Lucia (+1758)' },
  { value: 'SD', label: 'Sudan (+249)' },
  { value: 'SR', label: 'Suriname (+597)' },
  { value: 'SZ', label: 'Swaziland (+268)' },
  { value: 'SE', label: 'Sweden (+46)' },
  { value: 'CH', label: 'Switzerland (+41)' },
  { value: 'SI', label: 'Syria (+963)' },
  { value: 'TW', label: 'Taiwan (+886)' },
  { value: 'TJ', label: 'Tajikstan (+7)' },
  { value: 'TH', label: 'Thailand (+66)' },
  { value: 'TZ', label: 'Tanzania - United Rebublic (+255)' },
  { value: 'TG', label: 'Togo (+228)' },
  { value: 'TO', label: 'Tonga (+676)' },
  { value: 'TT', label: 'Trinidad & Tobago (+1868)' },
  { value: 'TN', label: 'Tunisia (+216)' },
  { value: 'TR', label: 'Turkey (+90)' },
  { value: 'TM', label: 'Turkmenistan (+7)' },
  { value: 'TM', label: 'Turkmenistan (+993)' },
  { value: 'TC', label: 'Turks & Caicos Islands (+1649)' },
  { value: 'TV', label: 'Tuvalu (+688)' },
  { value: 'UG', label: 'Uganda (+256)' },
  { value: 'GB', label: 'UK (+44)' },
  { value: 'UA', label: 'Ukraine (+380)' },
  { value: 'AE', label: 'United Arab Emirates (+971)' },
  { value: 'UY', label: 'Uruguay (+598)' },
  { value: 'US', label: 'USA (+1)' },
  { value: 'UZ', label: 'Uzbekistan (+7)' },
  { value: 'VU', label: 'Vanuatu (+678)' },
  { value: 'VA', label: 'Vatican City (+379)' },
  { value: 'VE', label: 'Venezuela (+58)' },
  { value: 'VN', label: 'Vietnam (+84)' },
  { value: 'VG', label: 'Virgin Islands - British (+1284)' },
  { value: 'VI', label: 'Virgin Islands - US (+1340)' },
  { value: 'WF', label: 'Wallis & Futuna (+681)' },
  { value: 'YE', label: 'Yemen (North)(+969)' },
  { value: 'YE', label: 'Yemen (South)(+967)' },
  { value: 'ZM', label: 'Zambia (+260)' },
  { value: 'ZW', label: 'Zimbabwe (+263)' },
]